autolabeler:
  - label: 'doc'
    files:
      - '*.md'
  - label: 'feature'
    title:
      - '/(support|feature)/i'
  - label: 'bug'
    title:
      - '/fix/i'
  - label: 'internal'
    title:
      - '/internal/i'
  - label: 'deprecation'
    title:
      - '/deprecate/i'
